Repository AndreRichartzFarias/Atividade-6---Desenvolvimento-de-Website-para-Brecho-Online, pull requests merged in 2025-03, with the labels that each got.

#4 feat: criado estrutura index.html #3
  index.html
Labels: feature

#10 feat: criado header #5
  index.html
  style.css
Labels: feature

#12 Fix 11: compatibilidade header e main
  index.html
  style.css
Labels: fix

#14 feat: criado footer #13
  index.html
  style.css
Labels: feature

#19 fix: enviado mudanças index.html e style.css #18
  index.html
  style.css
Labels: fix

#21 feat: formulario adicionado #20
  index.html
  style.css
Labels: feature

#22 Dev para main - publicação oficial
  index.html
  style.css
Labels: Offical Merge
